// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_qPDkoaQ3pcfOVuKhDsrSP3fAF7xghuE',
    appId: '1:905102236686:web:5758b19b49b51c9dff705f',
    messagingSenderId: '905102236686',
    projectId: 'check-in-app-dfa40',
    authDomain: 'check-in-app-dfa40.firebaseapp.com',
    storageBucket: 'check-in-app-dfa40.firebasestorage.app',
    measurementId: 'G-ZTFDQXJ1GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeJSYG7IGHfQQItuZfXbNJfwHImgv3ZlA',
    appId: '1:905102236686:android:63d94c3f33013282ff705f',
    messagingSenderId: '905102236686',
    projectId: 'check-in-app-dfa40',
    storageBucket: 'check-in-app-dfa40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrqLmfB7ZiCZPMNP-6DQHJdJxtWhT0sZk',
    appId: '1:905102236686:ios:38ba57bf32cbd978ff705f',
    messagingSenderId: '905102236686',
    projectId: 'check-in-app-dfa40',
    storageBucket: 'check-in-app-dfa40.firebasestorage.app',
    iosBundleId: 'com.example.checkInApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrqLmfB7ZiCZPMNP-6DQHJdJxtWhT0sZk',
    appId: '1:905102236686:ios:38ba57bf32cbd978ff705f',
    messagingSenderId: '905102236686',
    projectId: 'check-in-app-dfa40',
    storageBucket: 'check-in-app-dfa40.firebasestorage.app',
    iosBundleId: 'com.example.checkInApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_qPDkoaQ3pcfOVuKhDsrSP3fAF7xghuE',
    appId: '1:905102236686:web:4d7ec37d9c3fe406ff705f',
    messagingSenderId: '905102236686',
    projectId: 'check-in-app-dfa40',
    authDomain: 'check-in-app-dfa40.firebaseapp.com',
    storageBucket: 'check-in-app-dfa40.firebasestorage.app',
    measurementId: 'G-11HBXHK3C7',
  );
}
